### ISSUE TITLE
Problems with modern browsers

### ISSUE THREAD

**Issue by davideng14** [Integralist/HTML5-Image-Slider-Game#3]
I just downloaded the plugin, and it's not working nothing well with Chrome. I'm having troubles grabbing the pieces.

**Comment by hendrawd** [comment]
Any update on this? I have the same problem too. It's not working on my android phone

**Comment by Integralist** [comment]
Hi @hendrawd I wrote this code over 4yrs ago and to be honest I've not looked at it since.

At this point in time I'm not looking to keep the code up to date, so feel free to crack open the code and have a poke around (you can either open a PR or fork the code if you prefer).
